name: denver-skyimage

services:
  capture:
    build: ./capture
    restart: unless-stopped
    volumes:
      - ./config.yaml:/config/config.yaml:ro,z
      - ./cameras.json:/config/cameras.json:ro,z
      - ./downloaded_images:/data/images:z

  web:
    build: ./web
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
    security_opt:
      - label=disable
    volumes:
      - ./cameras.json:/config/cameras.json:ro,z
      - ./config.yaml:/config/config.yaml:ro,z
      - ./downloaded_images:/data/images:z
      - ./events:/data/events:z
      - ${CONTAINER_SOCK:-${XDG_RUNTIME_DIR:-/run/user/1000}/podman/podman.sock}:/var/run/docker.sock:ro

  videogen:
    build: ./videogen
    restart: unless-stopped
    volumes:
      - ./cameras.json:/config/cameras.json:ro,z
      - ./downloaded_images:/data/images:ro,z
      - ./videos:/data/videos:z
